---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - patch
- apiGroups:
  - elasticsearch.k8s.webcenter.fr
  resources:
  - elasticsearches
  verbs:
  - get
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - roles/finalizers
  verbs:
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - roles/status
  verbs:
  - get
  - patch
  - update
