//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package object

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasicMultiPhaseObject) DeepCopyInto(out *BasicMultiPhaseObject) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasicMultiPhaseObject.
func (in *BasicMultiPhaseObject) DeepCopy() *BasicMultiPhaseObject {
	if in == nil {
		return nil
	}
	out := new(BasicMultiPhaseObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasicMultiPhaseObjectStatus) DeepCopyInto(out *BasicMultiPhaseObjectStatus) {
	*out = *in
	in.BasicObjectStatus.DeepCopyInto(&out.BasicObjectStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasicMultiPhaseObjectStatus.
func (in *BasicMultiPhaseObjectStatus) DeepCopy() *BasicMultiPhaseObjectStatus {
	if in == nil {
		return nil
	}
	out := new(BasicMultiPhaseObjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasicObject) DeepCopyInto(out *BasicObject) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasicObject.
func (in *BasicObject) DeepCopy() *BasicObject {
	if in == nil {
		return nil
	}
	out := new(BasicObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasicObjectStatus) DeepCopyInto(out *BasicObjectStatus) {
	*out = *in
	if in.IsOnError != nil {
		in, out := &in.IsOnError, &out.IsOnError
		*out = new(bool)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasicObjectStatus.
func (in *BasicObjectStatus) DeepCopy() *BasicObjectStatus {
	if in == nil {
		return nil
	}
	out := new(BasicObjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasicRemoteObject) DeepCopyInto(out *BasicRemoteObject) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasicRemoteObject.
func (in *BasicRemoteObject) DeepCopy() *BasicRemoteObject {
	if in == nil {
		return nil
	}
	out := new(BasicRemoteObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasicRemoteObjectStatus) DeepCopyInto(out *BasicRemoteObjectStatus) {
	*out = *in
	in.BasicObjectStatus.DeepCopyInto(&out.BasicObjectStatus)
	if in.IsSync != nil {
		in, out := &in.IsSync, &out.IsSync
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasicRemoteObjectStatus.
func (in *BasicRemoteObjectStatus) DeepCopy() *BasicRemoteObjectStatus {
	if in == nil {
		return nil
	}
	out := new(BasicRemoteObjectStatus)
	in.DeepCopyInto(out)
	return out
}
