name: "build"

on:
  push:
    branches:
      - main
      - v2
    tags:
      - "*"
  pull_request:
    branches:
      - main
      - v2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dagger
        uses: dagger/dagger-for-github@v7
        with:
          version: 0.14.0
          call: --src . ci --ci --git-token env:GITHUB_TOKEN --code-cove-token env:CODECOV_TOKEN ${BRANCH_NAME} ${IS_TAG} ${IS_PR}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          IS_TAG: ${{ github.ref_type == 'tag' && '--is-tag' || '' }}
          IS_PR: ${{ github.event_name == 'pull_request' && '--is-pull-request' || '' }}
          BRANCH_NAME: ${{ github.event_name == 'pull_request' && format('--branch-name {0}', github.head_ref) || format('--branch-name {0}', github.ref) }}